[package]
name = "fossil-green"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
rusoto_ce = "0.36.0"
rusoto_core = "0.36.0"
rusoto_credential = "0.15.0"
structopt = "0.2"
itertools = "0.8.2"
